---
title: "Problem Set 5"
author: "Rana Bansal"
date: "10/26/2018"
output: html_document
---

```{r setup, include = FALSE}
## Here we load the necessary R packages for completing this assignment and doing all the necessary analysis. 
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(knitr)
library(openintro)
library(fs)
library(utils)
library(dplyr)
library(janitor)
library(BBmisc)
library(stringr)
library(lubridate)
```

## Question 1
```{r, echo = FALSE}
## Download the data for candidates. Then, unzip the folder that it is downloaded in. 
download.file(url = "https://www.fec.gov/files/bulk-downloads/2008/weball08.zip", 
              destfile = "weball08.zip")
unzip("weball08.zip")
```

```{r, echo = FALSE, message = FALSE, cache = TRUE}
## Now, we read in the data and provide information for how to sort it into columns.
## We provide names for our columns of interest using transmute function. 
candidates <- read_delim("weball08.txt", delim = "|", col_names = FALSE, escape_double = FALSE) %>%
  transmute(cand_id = X1, 
            cand_name = X2, 
            party = X5, 
            cash = X11, 
            cand_state = X19)

## Next, we replace those states with "00" as "No State" as 00 does not make sense.
candidates$cand_state <- gsub("00", "No State", candidates$cand_state)

## We create a data frame for states with the most rows, and we start by grouping by state.
## Next, we calculate the total number of rows for each state group.
## Then, we arrange state groups by the number of rows in in descending order. 
state_most_rows <- candidates %>%
  group_by(cand_state) %>%
  summarize(state_total = sum(cand_state == cand_state)) %>%
  arrange(desc(state_total))

## Take the first value of the data frame listing the states with most rows and add to string. 
cat(paste0("The state with the most rows is ", abbr2state(state_most_rows$cand_state[1]), "."))

## This is a capitalization function (inspired by posting on stack overflow) 
## Source here: https://stackoverflow.com/questions/6364783/capitalize-the-first-letter-of-both-words-in-a-two-word-string
capital <- function(x) {
  s <- strsplit(tolower(x), " ")[[1]]
  paste(toupper(substring(s, 1, 1)), substring(s, 2),
      sep = "", collapse = " ")
}

## This is a name formatting function (inspired by posting on stack overflow) 
## Source here: https://stackoverflow.com/questions/33826650/last-name-first-name-to-first-name-last-name
name_format <- function(name) {
  name_capitalized <- capital(name) 
  split_name <- strsplit(name_capitalized, ",")[[1]]
  paste(trimws(split_name[2]), split_name[1])
}

## We create a new variable for name length that is the number of characters in candidates name.
## We then arrange in descending order of this length with the top item of the table being longest name. 
longest_name <- candidates %>%
  mutate(name_length = nchar(cand_name)) %>%
  arrange(desc(name_length))

## We select the top item from that list that we found, put in appropriate format, and report the result. 
cat(paste0("The candidate with the longest full name is ", name_format(longest_name$cand_name[1]), "."))

## We first create a last name variable by selecting the first component of the cand_name variable.
## Then, we find the length of the last name using the nchar command.
## Finally, we arrange in descending order of the length of last name.
longest_last_name <- candidates %>%
  mutate(last_name = word(cand_name, 1)) %>%
  mutate(last_name_length = nchar(last_name)) %>%
  arrange(desc(last_name_length))

## We select the top item from that list that we found, put in appropriate format, and report the result.
cat(paste0("The candidate with the longest last name is ", name_format(longest_last_name$cand_name[1]), "."))

## We create a function for formatting the money in a format that is readable and appropriate using formatC. 
formatting_money  <- function(x) {
  paste0("$", formatC(as.numeric(x), format = "f", digits = 0, big.mark = ","))
}

## Here we are creating full names based on the party codes using the guidelines on FEC website.
## We select the necessary columns that we need and then we find the total cash per party. 
## We arrange in descending order. 
top_money <- candidates %>%
  select(cand_id, cand_name, party, cash, cand_state) %>%
  mutate(new_party = case_when(
    party == "AMP" ~ "American Party",
    party == "CON" ~ "Constitution Party",
    party == "CRV" ~ "Conservative Party",
    party == "CST" ~ "Constitutional Party",
    party == "DEM" ~ "Democratic Party",
    party == "Dem" ~ "Democratic Party",
    party == "DFL" ~ "Democratic-Farmer-Labor",
    party == "FRE" ~ "Freedom Party",
    party == "GRE" ~ "Green Party",
    party == "IND" ~ "Independent",
    party == "JCN" ~ "Jewish/Christian National",
    party == "LIB" ~ "Liberal Party",
    party == "NNE" ~ "None",
    party == "NPA" ~ "No Party Affiliation",
    party == "OTH" ~ "Other",
    party == "REF" ~ "Reform",
    party == "REP" ~ "Republican Party",
    party == "Rep" ~ "Republican Party",
    party == "RTL" ~ "Right To Life Party",
    party == "SOC" ~ "Socialist Party U.S.A.",
    party == "TLP" ~ "American",
    party == "N/A" ~ "Not Applicable",
    party == "NA" ~ "Not Applicable",
    TRUE ~ "Information Not Included"
  )) %>%
  group_by(new_party) %>%
  summarize(total_cash = sum(cash)) %>%
  mutate(new_cash = formatting_money(total_cash)) %>%
  arrange(desc(total_cash)) %>%
  select(new_party, new_cash)

## We print out the 5 political parties with the highest donations from the table above. 
head(top_money, 5) %>%
  kable(col.names = c("Political Party", "Total Cash Holdings"))
```

## Question 2
```{r, echo = FALSE, message = FALSE, cache = TRUE}
## We download the committee data to be used in the following analysis.
download.file(url = "https://www.fec.gov/files/bulk-downloads/2008/cm08.zip", destfile = "commiteedata.zip")
## We unzip the folder into which the data is downloaded.
unzip("commiteedata.zip")
## We read the data into R.
committee <- read_delim("cm.txt", delim = "|", col_names = FALSE, escape_double = FALSE) 
```

```{r, echo = FALSE}
## We create the variables of interest using the data we read in.
## We consolidate the relevant party variables based on abbreviation, which takes different cases.
condensed_committee <- committee %>% 
  transmute(cand_id = X15, cmte_id = X1, cmte_party = X11) %>% 
  filter(!is.na(cmte_party)) %>%
  mutate(cmte_party = case_when(tolower(cmte_party) == "rep" ~ "Republican",
                                tolower(cmte_party) == "dem" ~ "Democrat",
                                TRUE ~ "Other"))

## We group by party and then count the distinct values for candidates and committee. 
## We arrange in the order of distinct candidates, just so that the table looks good. 
committee_summary <- condensed_committee %>% 
  group_by(cmte_party) %>% 
  summarize(distinct_cand = n_distinct(cand_id),
            distinct_cmte = n_distinct(cmte_id)) %>%
  arrange(desc(distinct_cand))

## Finally, we report the final table using kable function.
## We add a caption and appropriate column names so the table looks good. 
committee_summary %>% 
  kable(caption = "Number of Distinct Candidates and Committees by Party",
        col.names = c("Political Party", "Unique Candidates", "Unique Committees"))
```

## Question 3
```{r downloads3, message = FALSE, cache = TRUE, include = FALSE}
## Here, we download the individual contribution data. 
download.file(url = "https://www.fec.gov/files/bulk-downloads/2008/indiv08.zip", destfile = "indiv_data.zip")
## We unzip the folder into which the data is downloaded.
unzip("indiv_data.zip")
## We read the data into R.
indiv_contrib <- read_delim("itcont.txt", delim = "|", col_names = FALSE, escape_double = FALSE) 
```

```{r, echo = FALSE}
## We join together the all candidates and the committee data here. 
candidates_committee <- left_join(candidates, condensed_committee, 
                       by = "cand_id") %>% 
  select(cand_id, cmte_id, party)

## We create a condensed version of individual contribution data to use in this part. 
condensed_indiv <- indiv_contrib %>% 
  transmute(cmte_id = X1, date = X14, amount = X15, name = X8, employer = X12, occupation = X13) 

## We next link the individual and committee data together and slect variables we want.
## We only want those employed by harvard who are professors and who have a party.
## Finally, we only want those who actually contributed (donated positive amount).
linked_donations <- left_join(condensed_indiv, candidates_committee, 
                       by = "cmte_id") %>% 
  select(party, date, amount, employer, occupation, name) %>% 
  mutate(date = mdy(date)) %>% 
  filter(employer == "HARVARD UNIVERSITY",
         str_detect(tolower(occupation), "professor")) %>% 
  filter((!is.na(party))) %>%
  filter(amount > 0)

## We update the dates using the floor_date function as we want quarterly data.
## We summarize the total number in each polical party. 
## Finally, we arrange the quarterly data. 
updated_dates <- linked_donations %>%
  mutate(quarterly = floor_date(date, "3 months")) %>%
  group_by(quarterly) %>% 
  summarize(DEM = sum(tolower(party) == "dem"),
            REP = sum(tolower(party) == "rep"),
            OTHER = sum(!tolower(party) %in% c("dem", "rep"))) %>%
  arrange(quarterly)

updated_dates %>%
  kable(caption = "Number of Donations, by quarter and political party",
          col.names = c("Quarter Start Date", "Democrat", "Republican", "Other"))
```

## Question 4
```{r, echo = FALSE}
## We create the dataset of all the donors that are employed by Harvard University.
all_donor <- left_join(condensed_indiv, candidates_committee, 
                       by = "cmte_id") %>% 
  select(party, date, amount, employer, occupation, name) %>% 
  mutate(date = mdy(date)) %>% 
  filter(employer == "HARVARD UNIVERSITY")

## Again, we find the party affiliations of all the Harvard donors and look at quarterly contribution.
## We sum the total amounts of contributions for quarter by party. 
all_donor_edited <- all_donor %>%
  mutate(party_affil = case_when(tolower(party) == "rep" ~ "Republican",
                                tolower(party) == "dem" ~ "Democrat",
                                TRUE ~ "Other")) %>%
  mutate(quarterly = floor_date(date, "3 months")) %>%
  arrange(quarterly) %>%
  mutate(party_affil = fct_relevel(party_affil, "Democrat", "Republican", "Other")) %>%
  group_by(quarterly, party_affil) %>%
  summarize(donation_total = sum(amount))

ggplot(all_donor_edited, aes(x = quarterly, y = donation_total, fill = party_affil)) + geom_bar(position = "stack", stat = "identity")
```

## Collaborators
Maddie Chai, Sean Hughes
